### ISSUE TITLE
Can't get it working on Kubernetes 1.8 running on AWS.

### ISSUE THREAD

**Issue by vutoff** [ApsOps/kube-nginx-websocket#1]
I'm trying to get it working on kubernetes 1.8 running on AWS. 
My Service and Deployment looks like:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-socket
  namespace: staging
  labels:
    run: nginx-socket
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31110
  selector:
    run: nginx-socket
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-socket
  namespace: staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-socket
    spec:
      containers:
      - name: nginx-socket
        image: apsops/kube-nginx-websocket:v0.2
        ports:
        - containerPort: 80
        env:
          - name: SOCKET_SERVER
            value: api-node-service
```
I've created an ELB and attached policy to enable ProxyProtocol. ELB successfully pass the requests to the Nginx but then I get the following error:

```
2017/10/23 15:57:48 [error] 8#8: *773 broken header: "GET / HTTP/1.1
host: api.vbroker.link
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en,bg;q=0.9,en-US;q=0.8
Cache-Control: no-cache
Cookie: _ga=GA1.2.1636843399.1505977898; session=s%3A1A9dXa2Axx-GXXjZRiFx7qvdIIj1_SG5.DsLG5EMrvAqBZCfXehBoE%2Bq6o7O4VqWT1lLSnrRhJ2I; AWSELB=E38D5B5512337D141F8A24D15DC7736D1367F6DACE3C8F108E445C9B9CDF08614EE5538F4DEBAE9F3BE71A55045486FD3404D60F8E6A4B52D76E466751D5456AF6DA132AEA535134EAE35E831C7D1D315B62DEE2C2
Pragma: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36
X-Forwarded-For: 87.121.146.7
X-Forwarded-Port: 443
X-Forwarded-Proto: https
Connection: keep-alive

" while reading PROXY protocol, client: 100.117.240.0, server: 0.0.0.0:80
```
